version: '3.8'

services:
  vulnerable-webcam:
    build: ./iot-devices/vulnerable-webcam
    container_name: vulnerable-webcam
    networks:
      iot-net:
        ipv4_address: 172.28.0.10
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    environment:
      # This address points to the Docker host's gateway, allowing the container
      # to reach the CALDERA server running on the host machine.
      - CALDERA_SERVER=http://172.28.0.1:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
